# A locally rebuilt Qt plugin must not silently cross a Qt ABI version change.
set(EISKALT_QCOCOA_PLUGIN_OVERRIDE "" CACHE FILEPATH "Patched Qt 6.11.1 Cocoa platform plugin")
set(EISKALT_QCOCOA_PLUGIN_SHA256 "" CACHE STRING "Verified SHA256 of the patched Cocoa plugin")
if(EISKALT_QCOCOA_PLUGIN_OVERRIDE)
    if(NOT Qt6Core_VERSION VERSION_EQUAL "6.11.1")
        message(FATAL_ERROR "The Cocoa backport requires Qt 6.11.1; clear EISKALT_QCOCOA_PLUGIN_OVERRIDE after upgrading Qt")
    endif()
    if(NOT EXISTS "${EISKALT_QCOCOA_PLUGIN_OVERRIDE}")
        message(FATAL_ERROR "Patched Cocoa plugin is missing: ${EISKALT_QCOCOA_PLUGIN_OVERRIDE}")
    endif()
    file(SHA256 "${EISKALT_QCOCOA_PLUGIN_OVERRIDE}" actualHash)
    if(NOT actualHash STREQUAL EISKALT_QCOCOA_PLUGIN_SHA256)
        message(FATAL_ERROR "Cocoa plugin SHA256 mismatch; rebuild/test the plugin and update EISKALT_QCOCOA_PLUGIN_SHA256")
    endif()
    set(requiredArchitectures ${CMAKE_OSX_ARCHITECTURES})
    if(NOT requiredArchitectures)
        set(requiredArchitectures ${CMAKE_SYSTEM_PROCESSOR})
    endif()
    if(NOT requiredArchitectures)
        message(FATAL_ERROR "Cannot validate Cocoa plugin without a target architecture")
    endif()
    foreach(arch IN LISTS requiredArchitectures)
        execute_process(COMMAND /usr/bin/lipo "${EISKALT_QCOCOA_PLUGIN_OVERRIDE}" -verify_arch "${arch}"
            RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cocoa plugin does not contain architecture ${arch}")
        endif()
        execute_process(COMMAND /usr/bin/otool -arch "${arch}" -L "${EISKALT_QCOCOA_PLUGIN_OVERRIDE}"
            RESULT_VARIABLE result OUTPUT_VARIABLE libraries ERROR_QUIET)
        foreach(module Core Gui)
            if(NOT result EQUAL 0 OR NOT libraries MATCHES "@rpath/Qt${module}\\.framework/Versions/A/Qt${module}[^\n]*current version 6\\.11\\.1\\)")
                message(FATAL_ERROR "Cocoa plugin ${arch} must link bundled Qt${module} 6.11.1")
            endif()
        endforeach()
    endforeach()
    set(EISKALT_QCOCOA_PLUGIN "${EISKALT_QCOCOA_PLUGIN_OVERRIDE}")
endif()
