find_package(c-ares 1.18.1 CONFIG QUIET)
if(TARGET c-ares::cares_static)
    set(EISKALT_CARES_TARGET c-ares::cares_static)
elseif(TARGET c-ares::cares)
    set(EISKALT_CARES_TARGET c-ares::cares)
else()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(CARES REQUIRED IMPORTED_TARGET libcares>=1.18.1)
    set(EISKALT_CARES_TARGET PkgConfig::CARES)
endif()
